def departments(web):
    if web == True:
        return [
            "Accounting",
            "Adv Intensive Arabic Study",
            "American Studies",
            "Anthropology",
            "Applied Linguistics",
            "Arab & Islamic Civilizations",
            "Arabic Lang. Intensive",
            "Arabic Language",
            "Arabic Language Writing",
            "Architectural Engineering",
            "Biology",
            "Biotechnology",
            "Business Administration",
            "Chemistry",
            "Computer Science & Engineering",
            "Construction Engineering",
            "Core Curriculum",
            "Data Science",
            "Economics",
            "Education",
            "Egyptology",
            "Electronics & Communications Eng",
            "Engineering",
            "English & Comparative Lit.",
            "Entrepreneurship",
            "Environmental Engineering",
            "Film",
            "Finance",
            "Foreign Languages",
            "Gender and Women's Studies",
            "Global Health & Human Ecology",
            "Graphic Design",
            "History",
            "International MGMT/CEMS",
            "Journalism and Mass Com.",
            "Law",
            "Libraries & Learning Tech.",
            "Linguistics",
            "Management",
            "Management of Information Sys",
            "Marketing",
            "Math & Actuarial Science",
            "Mechanical Eng.",
            "Middle East Studies",
            "Migration and Refugee Studies",
            "Music",
            "Nanotechnology",
            "Operations/Production MGMT",
            "Petroleum & Energy Engineering",
            "PhD Applied Science",
            "PhD Engineering",
            "Philosophy",
            "Physics",
            "Political Science",
            "Psychology",
            "Public Policy & Administration",
            "Rhetoric and Composition",
            "Robotics Contrl & Smart Syst.",
            "SCIENCE",
            "SEMINAR",
            "SOCIOLOGY",
            "Sustainable Development",
            "THEATRE",
            "TV. & Digital Journalism",
            "Visual Art",
        ]
    else:
        return {
            "Accounting": "ACCT",
            "Adv Intensive Arabic Study": "AIAS",
            "American Studies": "AMST",
            "Anthropology": "ANTH",
            "Applied Linguistics": "APLN",
            "Arab & Islamic Civilizations": "ARIC",
            "Arabic Lang. Intensive": "ALIN",
            "Arabic Language": "ALNG",
            "Arabic Language Writing": "ALWT",
            "Architectural Engineering": "ARCH",
            "Biology": "BIOL",
            "Biotechnology": "BIOT",
            "Business Administration": "BADM",
            "Chemistry": "CHEM",
            "Computer Science & Engineering": "CSCE",
            "Construction Engineering": "CENG",
            "Core Curriculum": "CORE",
            "Data Science": "DSCI",
            "Economics": "ECON",
            "Education": "EDUC",
            "Egyptology": "EGPT",
            "Electronics & Communications Eng": "ECNG",
            "Engineering": "ENGR",
            "English & Comparative Lit.": "ECLT",
            "Entrepreneurship": "ENTR",
            "Environmental Engineering": "ENVE",
            "Film": "FILM",
            "Finance": "FINC",
            "Foreign Languages": "FLNG",
            "Gender and Women's Studies": "GWST",
            "Global Health & Human Ecology": "GHHE",
            "Graphic Design": "DSGN",
            "History": "HIST",
            "International MGMT/CEMS": "CEMS",
            "Journalism and Mass Com.": "JRMC",
            "Law": "LAW",
            "Libraries & Learning Tech.": "LALT",
            "Linguistics": "LING",
            "Management": "MGMT",
            "Management of Information Sys": "MOIS",
            "Marketing": "MKTG",
            "Math & Actuarial Science": "MACT",
            "Mechanical Eng.": "MENG",
            "Middle East Studies": "MEST",
            "Migration and Refugee Studies": "MRS",
            "Music": "MUSC",
            "Nanotechnology": "NANO",
            "Operations/Production MGMT": "OPMG",
            "Petroleum & Energy Engineering": "PENG",
            "PhD Applied Science": "PHDS",
            "PhD Engineering": "PHDE",
            "Philosophy": "PHIL",
            "Physics": "PHYS",
            "Political Science": "POLS",
            "Psychology": "PSYC",
            "Public Policy & Administration": "PPAD",
            "Rhetoric and Composition": "RHET",
            "Robotics Contrl & Smart Syst.": "RCSS",
            "SCIENCE": "SCI",
            "SEMINAR": "SEMR",
            "SOCIOLOGY": "SOC",
            "Sustainable Development": "GREN",
            "THEATRE": "THTR",
            "TV. & Digital Journalism": "TVDJ",
            "Visual Art": "ARTV",
        }
